os:
  - osx
  - linux
  - windows

language: node_js

node_js:
  - 12
  - 10

cache: cargo

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.rs
    chmod +x ./rustup.rs
    ./rustup.rs -y
    source $HOME/.cargo/env
    yarn global add neon-cli
    fi;
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'; fi;
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -File scripts\\install_rustup.ps1; fi;


  # Install NPM packages
  - node -v
  - npm -v
  - echo $TRAVIS_NODE_VERSION
  - yarn
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then yarn cross-env npm_config_target=6.0.7 npm_config_arch=x64 npm_config_disturl=https://electronjs.org/headers npm_config_runtime=electron neon build --release; fi;
  # First build for electron 6 to get that ABI. Other header rebuilds work fine from there.
  - if [[ ${TRAVIS_TAG} != "" ]]; then yarn neon-build-electron; fi;
  # remove native folder to prevent packaging EVERYTHING
  - rm -rf native/target


script:
  # - npm test
  # Publish when using '[publish binary]' keywords
  - COMMIT_MESSAGE=$(git log --format=%B --no-merges -n 1 | tr -d '\n')
  - if [[ ${TRAVIS_TAG} != "" ]]; then NODE_PRE_GYP_GITHUB_TOKEN=$GITHUB_ACCESS_TOKEN yarn upload-binaries || exit 0; fi;
