name: Version Bump and Tag

on:
  # Trigger the workflow on push only for the master branch
  push:
    branches:
      - master

env:
  NODE_ENV: 'development'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Setup git
        run: |
          git remote add github "$REPO"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Bump Version
        run: npx standard-version -a 
      - name: Push changes to master
        run: git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY" HEAD:master

      - name: Push tag
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN}}
        run: git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY" HEAD:master --tags

  
  