name: Tests

on: [pull_request, push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SAFE_CLI_VERSION: "0.10.1"

jobs:
  tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Download Safe CLI
        run:  |
          wget "https://github.com/maidsafe/safe-api/releases/download/${{env.SAFE_CLI_VERSION}}/safe-cli-${{env.SAFE_CLI_VERSION}}-x86_64-unknown-linux-gnu.tar.gz" -O ./safe.tar.gz;
          ls .
          mkdir -p $HOME/.safe/safe-cli
          mkdir -p $HOME/.safe/authd
          mkdir -p $HOME/.config/safe-authd
          tar -xvzf ./safe.tar.gz -C $HOME/.safe/safe-cli/
          echo "::add-path::$HOME/.safe/safe-cli"
          echo "::add-path::$HOME/.safe/authd"
          chmod +x $HOME/.safe/safe-cli/safe
        if: matrix.os == 'ubuntu-latest'
      - name: Install Safe AuthD
        run: |
          safe auth install
          chmod +x $HOME/.safe/authd/safe-authd
        if: matrix.os == 'ubuntu-latest'
      - name: Download Vault And Setup Folders
        run: |
          mkdir -p $HOME/.safe/vault
          wget https://safe-vault.s3.eu-west-2.amazonaws.com/safe_vault_lionel_pr_no_parsec.zip
          unzip safe_vault_lionel_pr_no_parsec.zip -d $HOME/.safe/vault
          chmod +x $HOME/.safe/vault/safe_vault
          ls $HOME/.safe/safe-cli
          ls $HOME/.safe/authd
          ls $HOME/.safe/vault
          echo $PATH
      - run : yarn
      - name: Mock Tests
        run: |
          yarn build-mock
          yarn test-api
      - run : safe vault run-baby-fleming
      - name: Mini-Network Tests
        run: |
          yarn build
          yarn test-auth
